import "./detection.test.js";
import "./providers.test.js";
import "./prioritize.test.js";
import "./controller.test.js";
import "./extension.test.js";
import "./cache.test.js";
import "./lock.test.js";
import "./status.test.js";
import "./keybindings.test.js";
